services:
  app:
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile.server
    ports:
      - "5000:5000"
    env_file:
      - .local/server.env
    environment:
      - STAGE=dev
    volumes:
      - ./service_accounts:/app/service_accounts:ro
      - ./data_dev:/tmp
  backend:
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile.backend_only
    ports:
      - "5000:5000"
    env_file:
      - .local/server.env
    environment:
      - STAGE=dev
    volumes:
      - ./service_accounts:/app/service_accounts:ro
      - ./data_dev:/tmp
  pipeline-load:
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile.pipe
    env_file:
      - .local/elt.env
    volumes:
      - ./service_accounts:/app/service_accounts:ro
      - ./devops:/app/devops:ro
    command: ["bash", "/app/devops/run_pipeline.sh"]
  pipeline-load-full-refresh:
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile.pipe
    env_file:
      - .local/elt.env
    volumes:
      - ./service_accounts:/app/service_accounts:ro
      - ./devops:/app/devops:ro
    command: ["bash", "/app/devops/run_pipeline.sh", "--full-refresh"]
  pipeline-shell:
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile.pipe
    env_file:
      - .local/elt.env
    volumes:
      - ./service_accounts:/app/service_accounts:ro
      - ./src/analytics:/app/src/analytics
    command: ["sleep", "infinity"]