[project]
name = "health-metrics"
version = "0.1.0"
description = "A data pipeline and full-stack web application to track my fitness progress"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "bigframes",
    "klondike",
    "click==8.3.1",
    "flask==3.1.2",
    "gunicorn",
    "colorlog",
    "google-cloud-storage",
    "google-cloud-bigquery",
    "google-cloud-logging",
    "pandas",
    "resend>=2.22.0",
    "google-genai>=1.65.0",
]

[dependency-groups]
development = ["ruff>=0.15.17", "pre-commit>=4.6.0"]


[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
extend-ignore = [
    "F401",
    "E203",
    "E266",
    "E402",
    "E501",
    "E711",
    "E712",
    "F403",
    "F821",
]
select = ["E", "F", "I"]


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"
