FROM python:3.12-bullseye

WORKDIR /app

COPY pyproject.toml .
RUN pip install uv && uv sync

COPY ./src /app/src
COPY ./common /app/src/common

ENV PYTHONPATH="/app/src:${PYTHONPATH}"

WORKDIR /app/src/analytics
RUN uv run dbt deps

WORKDIR /app