FROM python:3.12-bullseye

WORKDIR /app

COPY pyproject.toml .
RUN pip install uv && uv sync

COPY ./app/backend .
COPY ./common ./common

RUN mkdir -p ./frontend/dist

ENV PYTHONPATH="/app:/app/common"
EXPOSE 5000

CMD ["uv", "run", "gunicorn", "-b", "0.0.0.0:5000", "--timeout", "300", "wsgi"]