FROM python:3.12-bullseye

WORKDIR /app

COPY ./devops/dependencies/pipeline-requirements.txt /app/pipeline-requirements.txt
RUN pip install -r /app/pipeline-requirements.txt

COPY ./src /app/src
COPY ./common /app/src/common

ENV PYTHONPATH="/app/src:${PYTHONPATH}"

WORKDIR /app/src/analytics
RUN dbt deps

WORKDIR /app