name: 'health_metrics'
version: '1.0.0'

profile: 'health_metrics'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:     
  - "target"
  - "dbt_packages"

# Set all tests to warn instead of fail
data_tests:
  +severity: warn  

models:
  health_metrics:
    +persist_docs:
      +persist_docs:
      relation: true
      columns: true
    +submission_method: serverless
    +materialized: table

    # Layer-specific overrides
    base:
      +schema: health_metrics_base
      +materialized: view
      +tags: ["base"]

    staging:
      +schema: health_metrics_staging
      +tags: ["staging"]

    analytics:
      # We'll flip this on later
      +enabled: false
      machine_learning:
        +schema: health_metrics_ml
        +tags: ["machine_learning"]
      +schema: health_metrics_analytics
      +tags: ["analytics"]
  
