health_metrics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: ian-is-online
      dataset: dbt
      threads: 4
      keyfile: /app/service_accounts/ian-is-online-e8d79794493b.json
      location: us
    
    cloud:
      type: bigquery
      method: oauth
      project: ian-is-online
      dataset: dbt
      threads: 4
      location: us